// request past portfolio data
const REQUEST_PORTFOLIO_HISTORY = 'REQUEST_PORTFOLIO_DATA'
// receive past portfolio data
const RECEIVE_PORTFOLIO_HISTORY = 'RECEIVE_PORTFOLIO_DATA'

const REQUEST_CURRENT_PORTFOLIO_DATA = 'REQUEST_CURRENT_PORTFOLIO_DATA'

const RECEIVE_CURRENT_PORTFOLIO_DATA = 'RECEIVE_CURRENT_PORTFOLIO_DATA'

// request account portfolio update
const REQUEST_PORTFOLIO_UPDATE = 'REQUEST_PORTFOLIO_UPDATE'

const ANNOUNCE_PORTFOLIO_UPDATE_COMPLETION = 'ANNOUNCE_PORTFOLIO_UPDATE_COMPLETION'

const REQUEST_HISTORICAL_STOCK_DATA = 'REQUEST_HISTORICAL_STOCK_DATA' 

const RECEIVE_HISTORICAL_STOCK_DATA = 'RECEIVE_HISTORICAL_STOCK_DATA'

const CALCULATE_PORTFOLIO_RETURN = 'CALCULATE_PORTFOLIO_RETURN'