import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import Store from './store';
import './index.css';
import App from './components/app/App';
import { BrowserRouter } from 'react-router-dom';
import registerServiceWorker from './registerServiceWorker';
import dotenv from 'dotenv';
dotenv.config();

// Provider provides global state of all components to App
// Provider is the only way to use store
// BrowserRouter uses the states provided by Provider
// The state is generated by Provider

ReactDOM.render(
<Provider store={Store}>
	<BrowserRouter>
		<App />
	</BrowserRouter>
</Provider>, document.getElementById('root'));
registerServiceWorker();